version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
     # copy the sql script to create tables
      - ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  pgweb:
    container_name: pgweb
    # restart: always
    image: sosedoff/pgweb
    ports: 
      - "8081:8081" 
    links: 
    # database container name is db
      - db:db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
    depends_on:
      - db
volumes:
  db:
    driver: local